Repository Seila-dev/watchlist, pull requests merged in 2025-08, with the labels that each got.

#6 feat: ModelCard modal reutilizável
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(private)/layout.tsx
  src/app/_components/ModalCard.tsx
  src/app/globals.css
  src/app/page.tsx
  src/components/ui/card.tsx
Labels: enhancement

#9 feat: add background, fix input and card styles
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/BackgroundEclipses.tsx
  src/components/ModalCard.tsx
  src/components/ui/card.tsx
  src/components/ui/input.tsx
Labels: enhancement

#14 fix: switch favicon to public
  public/favicon.ico
Labels: bug

#17 style: remove dark styling at authlayout
  src/app/(auth)/layout.tsx
Labels: style

#27 fix: fix shadcn styles (button, input, label) and add login auth with…
  src/app/(auth)/login/page.tsx
  src/components/GoogleLoginButton/GoogleLogin.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
Labels: enhancement, style

#29 style: fix responsive google button and login
  src/app/(auth)/login/page.tsx
  src/components/GoogleLoginButton/GoogleLogin.tsx
Labels: bug

#30 fix: fix registeraccount not working, authcontext, username conflicts
  src/components/GoogleLoginButton/GoogleLogin.tsx
  src/components/RegisterForm/RegisterForm.tsx
  src/contexts/AuthContext.tsx
  src/types/userData.ts
Labels: bug

#31 fix: google auth wrong route
  src/components/GoogleLoginButton/GoogleLogin.tsx
Labels: bug

#32 fix: remove dangerous console
  src/components/GoogleLoginButton/GoogleLogin.tsx
Labels: bug

#33 feat: create reset-password all flows, validate-code, new-password
  src/app/(auth)/reset-password/new-password/page.tsx
  src/app/(auth)/reset-password/new-password/schema.ts
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/reset-password/schema.ts
Labels: enhancement

#34 style: responive update and new fix
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/components/Modals/ModalCard.tsx
  src/components/ui/card.tsx
Labels: bug, style

#38 Feat/new password
  src/app/(auth)/reset-password/new-password/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/contexts/AuthContext.tsx
Labels: bug, enhancement

#40 feat: add temporary homepage for developing uses
  src/app/page.tsx
Labels: enhancement

#47 fix privateLayout
  src/app/(auth)/layout.tsx
  src/app/(private)/layout.tsx
Labels: bug

#55 test: new add-ons inside google login btn
  src/app/auth/google/callback/page.tsx
  src/components/GoogleLoginButton/GoogleLogin.tsx
  src/components/icons/GoogleIcon.tsx
Labels: enhancement

#63 feat: implement Header Component with logo, nav links, add button, no…
  src/components/Header/Header.tsx
Labels: enhancement

#64 Feat: creation home nav, search input and rating stars logic
  next.config.ts
  src/adapters/anime.ts
  src/adapters/contentToCard.ts
  src/app/(private)/home/page.tsx
  src/app/api/tmdb/route.ts
  src/components/Cards/CardPreview.tsx
  src/components/Nav/CategoryBar.tsx
  src/components/Nav/Nav.tsx
  src/components/Nav/SearchAutocomplete.tsx
  src/components/Rating/RatingStars.tsx
  src/hooks/useAnimeApi.ts
  src/hooks/useCategorySearch.ts
  src/hooks/useDebounce.ts
  src/hooks/useUserRating.ts
  src/lib/jikan.ts
  src/lib/tmdb.ts
  src/types/ApiTypes.ts
  src/types/tagsTypes.ts
Labels: enhancement

#72 refactor/feat: add new features to carousel, new bugs, minor fixes, upgrades
  .env.example
  src/app/(auth)/layout.tsx
  src/app/(private)/home/page.tsx
  src/app/(private)/layout.tsx
  src/app/layout.tsx
  src/components/Cards/CardCarousel.tsx
  src/components/Cards/CardPreview.tsx
  src/components/Cards/CarouselSkeleton.tsx
  src/components/Cards/useCarousel.tsx
  src/components/Header/Header.tsx
  src/components/Nav/Nav.tsx
  src/components/StatusLabel/index.tsx
  src/lib/jikan.ts
  src/lib/tmdb.ts
  src/lib/utils.ts
  src/types/ApiTypes.ts
  tailwind.config.js
Labels: bug, refactor

#71 Fix: checking and adjusting
  src/app/(auth)/register/validate-code/page.tsx
  src/app/(private)/home/page.tsx
  src/app/(private)/layout.tsx
  src/components/Cards/CardPreview.tsx
  src/components/Nav/Nav.tsx
  src/components/RegisterForm/RegisterForm.tsx
  src/contexts/AuthContext.tsx
  src/middleware.ts
  src/types/userData.ts
Labels: refactor

#73 fix: remove all apis except for jikan, cleaned most folders and fix carousel
  src/adapters/anime.ts
  src/adapters/contentToCard.ts
  src/app/(private)/home/page.tsx
  src/app/api/tmdb/route.ts
  src/components/Cards/CardCarousel.tsx
  src/components/Cards/CardPreview.tsx
  src/components/Nav/Nav.tsx
  src/components/Nav/SearchAutocomplete.tsx
  src/contexts/AuthContext.tsx
  src/hooks/useAnimeApi.ts
  src/hooks/useCategorySearch.ts
  src/hooks/useDebounce.ts
  src/hooks/useUserRating.ts
  src/lib/jikan.ts
  src/lib/tmdb.ts
  src/lib/utils.ts
  src/types/ApiTypes.ts
Labels: bug, refactor, style

#74 fix: add condition to middleware when user is logged in
  src/middleware.ts
Labels: bug

#75 chore: add jest, add middleware tests, refactor middleware.ts
  jest.config.js
  package-lock.json
  package.json
  src/middleware.test.ts
  src/middleware.ts
Labels: enhancement, refactor
